# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
            ],
        ),
    ]
