# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operational_user', '0001_initial'),
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer')),
                ('operational_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operational_user.Operational_user')),
            ],
        ),
    ]
