# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(unique=True)),
                ('options', models.ManyToManyField(to='Answer.Answer')),
            ],
        ),
    ]
